=== scc-digitalhub/AAC/application/src/main/resources/jaxb/binding/attributeSchema.xsd
<?xml version="1.0"?>
<!-- Copyright 2015-2019 Smart Community Lab, FBK Licensed under the Apache License, Version 
	2.0 (the "License"); you may not use this file except in compliance with 
	the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 
	Unless required by applicable law or agreed to in writing, software distributed 
	under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES 
	OR CONDITIONS OF ANY KIND, either express or implied. See the License for 
	the specific language governing permissions and limitations under the License. -->
<xsd:schema version="1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://aac.smartcommunitylab.it/jaxbmodel"
  xmlns:tns="http://aac.smartcommunitylab.it/jaxbmodel" elementFormDefault="qualified">
    <xsd:include schemaLocation=""></xsd:include>
    <xsd:element name="authorities" type="tns:authorities" />
	<xsd:complexType name="authorities">
		<xsd:annotation>
			<xsd:documentation>List of identity provider authorities.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="authorityMapping" type="tns:authorityMapping" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="authorityMatching" type="tns:authorityMatching" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="authorityMapping">
		<xsd:annotation>
			<xsd:documentation>Description of the authority. Characterized by the
				authority name, url path, identity attributes, other attributes, and
				whether the attributes are extracted from the request parameters or
				from attributes
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="attributes" type="tns:attributes" />
			</xsd:choice>
			<xsd:choice minOccurs="1" maxOccurs="unbounded">
				<xsd:element name="identifyingAttributes" type="xsd:string" />
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required" />
		<xsd:attribute name="url" type="xsd:string" use="required" />
		<xsd:attribute name="useParams" type="xsd:boolean" use="optional" default="false"/>
    <xsd:attribute name="public" type="xsd:boolean" use="optional" default="false"/>
    <xsd:attribute name="web" type="xsd:boolean" use="optional" default="true"/>
	</xsd:complexType>
	<xsd:complexType name="attributes">
		<xsd:annotation>
			<xsd:documentation>Attribute descriptor defined by the attribute
				value and optional (internal) alias</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="alias" type="xsd:string" use="optional" />
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	<xsd:complexType name="authorityMatching">
    <xsd:annotation>
      <xsd:documentation>Matching authorities for duplicate accounts</xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="authority" type="tns:match" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="match">
    <xsd:annotation>
      <xsd:documentation>Matching authority definition</xsd:documentation>
    </xsd:annotation>
    <xsd:attribute name="name" type="xsd:string" use="required" />
    <xsd:attribute name="attribute" type="xsd:string" use="required" />
  </xsd:complexType>
</xsd:schema>

=== scc-digitalhub/AAC/application/src/main/resources/it/smartcommunitylab/aac/manager/authorities.xml
<?xml version="1.0" standalone="yes"?>
<!--

       Copyright 2015-2019 Smart Community Lab, FBK

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

           http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->

<authorities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://aac.smartcommunitylab.it/jaxbmodel"  
  xsi:schemaLocation="http://aac.smartcommunitylab.it/jaxbmodel ../../../../../jaxb/binding/attributeSchema.xsd">

  <authorityMapping name="google" url="google" public="true" useParams="true">
      <attributes alias="it.smartcommunitylab.aac.givenname">given_name</attributes>
      <attributes alias="it.smartcommunitylab.aac.surname">family_name</attributes>
      <attributes alias="it.smartcommunitylab.aac.username">email</attributes>
      <attributes alias="it.smartcommunitylab.aac.email">email</attributes>
      <attributes>name</attributes>
      <attributes>link</attributes>
      <identifyingAttributes>email</identifyingAttributes>
  </authorityMapping>
  <authorityMapping name="facebook" url="facebook" public="true" useParams="true">
      <attributes alias="it.smartcommunitylab.aac.givenname">first_name</attributes>
      <attributes alias="it.smartcommunitylab.aac.surname">last_name</attributes>
      <attributes alias="it.smartcommunitylab.aac.username">email</attributes>
      <attributes alias="it.smartcommunitylab.aac.email">email</attributes>
      <identifyingAttributes>id</identifyingAttributes>
  </authorityMapping>
  <authorityMapping name="internal" url="internal" public="false" web="true"  useParams="false">
      <attributes alias="it.smartcommunitylab.aac.givenname">name</attributes>
      <attributes alias="it.smartcommunitylab.aac.surname">surname</attributes>
      <attributes alias="it.smartcommunitylab.aac.email">email</attributes>
      <attributes>email</attributes>
      <identifyingAttributes>email</identifyingAttributes>
  </authorityMapping>
  <authorityMapping name="adc" url="adc" public="false" web="true">
      <attributes alias="it.smartcommunitylab.aac.givenname">accounts.adc.eu.trentorise.smartcampus.surname</attributes>
      <attributes alias="it.smartcommunitylab.aac.surname">accounts.adc.eu.trentorise.smartcampus.givenname</attributes>
      <attributes alias="it.smartcommunitylab.aac.username">accounts.adc.pat_attribute_codicefiscale</attributes>
      <attributes alias="it.smartcommunitylab.aac.email">accounts.adc.pat_attribute_email</attributes>
      <attributes>accounts.adc.pat_attribute_capdomicilio</attributes>
      <attributes>accounts.adc.pat_attribute_capresidenza</attributes>
      <attributes>accounts.adc.pat_attribute_cellulare</attributes>
      <attributes>accounts.adc.pat_attribute_cittadomicilio</attributes>
      <attributes>accounts.adc.pat_attribute_cittaresidenza</attributes>
      <attributes>accounts.adc.pat_attribute_datanascita</attributes>
      <attributes>accounts.adc.pat_attribute_emailaddresspersonale</attributes>
      <attributes>accounts.adc.pat_attribute_indirizzodomicilio</attributes>
      <attributes>accounts.adc.pat_attribute_indirizzoresidenza</attributes>
      <attributes>accounts.adc.pat_attribute_luogonascita</attributes>
      <attributes>accounts.adc.pat_attribute_provinciadomicilio</attributes>
      <attributes>accounts.adc.pat_attribute_provincianascita</attributes>
      <attributes>accounts.adc.pat_attribute_provinciaresidenza</attributes>
      <attributes>accounts.adc.pat_attribute_sesso</attributes>
      <attributes>accounts.adc.pat_attribute_statodomicilio</attributes>
      <attributes>accounts.adc.pat_attribute_statonascita</attributes>
      <attributes>accounts.adc.pat_attribute_statoresidenza</attributes>
      <attributes>accounts.adc.pat_attribute_telefono</attributes>
      <attributes>accounts.adc.pat_attribute_titolo</attributes>
      <attributes>accounts.adc.pat_attribute_subjectdn</attributes>
      <attributes>accounts.adc.pat_attribute_issuerdn</attributes>
      <attributes>accounts.adc.pat_attribute_codicefiscale</attributes>
      <identifyingAttributes>accounts.adc.pat_attribute_codicefiscale</identifyingAttributes>
  </authorityMapping>
  <authorityMapping name="cie" url="cie" public="false" web="true">
      <attributes alias="it.smartcommunitylab.aac.givenname">accounts.cie.eu.trentorise.smartcampus.surname</attributes>
      <attributes alias="it.smartcommunitylab.aac.surname">accounts.cie.eu.trentorise.smartcampus.givenname</attributes>
      <attributes alias="it.smartcommunitylab.aac.username">accounts.cie.fiscalNumberId</attributes>
      <attributes alias="it.smartcommunitylab.aac.email">accounts.cie.email</attributes>
      <attributes alias="fiscalNumberId">accounts.cie.fiscalNumberId</attributes>
      <attributes alias="dateOfBirthId">accounts.cie.dateOfBirthId</attributes>
      <attributes alias="email">accounts.cie.email</attributes>
      <identifyingAttributes>accounts.cie.fiscalNumberId</identifyingAttributes>
  </authorityMapping>

  <authorityMatching>
      <authority name="google" attribute="email"/>
      <authority name="facebook" attribute="email"/>
      <authority name="internal" attribute="email"/>
  </authorityMatching>
  <authorityMatching>
      <authority name="facebook" attribute="id"/>
  </authorityMatching>
  <authorityMatching>
      <authority name="cie" attribute="accounts.cie.fiscalNumberId"/>
      <authority name="adc" attribute="accounts.adc.pat_attribute_codicefiscale"/>
  </authorityMatching>

</authorities>
